-- Create admins table
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL, -- In a real app, use proper hashing. For demo, we might store plain or simple hash.
    role TEXT NOT NULL CHECK (role IN ('master', 'sub')),
    name TEXT NOT NULL
);

-- Insert default Master Admin (password: admin123)
-- Note: In a real production app, NEVER store passwords in plain text or simple reversible formats.
-- We will assume the application handles hashing, or for this MVP, we might use a simple check.
INSERT INTO admins (email, password_hash, role, name)
VALUES 
('admin@mangaloreproperties.com', 'admin123', 'master', 'Master Admin')
ON CONFLICT (email) DO NOTHING;

-- Insert a Sub Admin for testing (password: sub123)
INSERT INTO admins (email, password_hash, role, name)
VALUES 
('partner@mangaloreproperties.com', 'sub123', 'sub', 'Partner Admin')
ON CONFLICT (email) DO NOTHING;
