
create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id text not null,
  property_id integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, property_id)
);
