-- Drop the table to reset
drop table if exists favorites;

-- Create a table compatible with our current "Mock Login" (Phone Numbers)
create table favorites (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Must be TEXT to store phone numbers (e.g., "9999999999")
  property_id text not null,
  property_type text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Prevent duplicates
  unique (user_id, property_id)
);

-- NOTE: We cannot use RLS (Row Level Security) yet because we are not using 
-- real Supabase Auth (supabase.auth.signIn). We are using a local mock login.
-- Once we upgrade to real Auth, we can enable RLS and use UUIDs.
