-- 1. Create 'builders' table
CREATE TABLE IF NOT EXISTS builders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    logo_url TEXT,
    year_est TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create 'projects' table
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    builder_id BIGINT REFERENCES builders(id) ON DELETE CASCADE,
    location TEXT,
    price_text TEXT,
    status TEXT,
    category TEXT,
    cover_image_url TEXT,
    gallery_images TEXT[], -- Array of text
    amenities TEXT[],      -- Array of text
    video_url TEXT,
    featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE builders ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies for Tables

-- Public Read Access (Builders)
DROP POLICY IF EXISTS "Public builders are viewable by everyone" ON builders;
CREATE POLICY "Public builders are viewable by everyone"
ON builders FOR SELECT
USING (true);

-- Admin Write Access (Builders) - Authenticated users only
DROP POLICY IF EXISTS "Authenticated users can insert builders" ON builders;
CREATE POLICY "Authenticated users can insert builders"
ON builders FOR INSERT
TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can update builders" ON builders;
CREATE POLICY "Authenticated users can update builders"
ON builders FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can delete builders" ON builders;
CREATE POLICY "Authenticated users can delete builders"
ON builders FOR DELETE
TO authenticated
USING (true);

-- Public Read Access (Projects)
DROP POLICY IF EXISTS "Public projects are viewable by everyone" ON projects;
CREATE POLICY "Public projects are viewable by everyone"
ON projects FOR SELECT
USING (true);

-- Admin Write Access (Projects) - Authenticated users only
DROP POLICY IF EXISTS "Authenticated users can insert projects" ON projects;
CREATE POLICY "Authenticated users can insert projects"
ON projects FOR INSERT
TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can update projects" ON projects;
CREATE POLICY "Authenticated users can update projects"
ON projects FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can delete projects" ON projects;
CREATE POLICY "Authenticated users can delete projects"
ON projects FOR DELETE
TO authenticated
USING (true);


-- 5. Storage Setup

-- Create a new public bucket 'property-images'
INSERT INTO storage.buckets (id, name, public)
VALUES ('property-images', 'property-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies

-- Public Read Access for Storage
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING ( bucket_id = 'property-images' );

-- Authenticated Insert/Update Access for Storage
DROP POLICY IF EXISTS "Authenticated Upload" ON storage.objects;
CREATE POLICY "Authenticated Upload"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'property-images' );

DROP POLICY IF EXISTS "Authenticated Update" ON storage.objects;
CREATE POLICY "Authenticated Update"
ON storage.objects FOR UPDATE
TO authenticated
USING ( bucket_id = 'property-images' );

DROP POLICY IF EXISTS "Authenticated Delete" ON storage.objects;
CREATE POLICY "Authenticated Delete"
ON storage.objects FOR DELETE
TO authenticated
USING ( bucket_id = 'property-images' );
