
-- Drop existing table to recreate with correct schema (simplest approach for dev)
drop table if exists favorites;

create table favorites (
  id bigint generated by default as identity primary key,
  user_id text not null,
  property_id text not null, -- Changed to text to support "c1", "r1" etc.
  property_type text not null, -- Added property_type
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, property_id)
);
